colors:
  # Default colors
  primary:
    background: '0x1e222a'
    foreground: '0xc8ccd4'

  # Normal colors
  normal:
    black:   '0x282c34'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xe5c07b'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  # Bright colors
  bright:
    black:   '0x545862'
    red:     '0xd19a66'
    green:   '0x98c379'
    yellow:  '0xe5c07b'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xc8ccd4'

