#! /bin/sh

sxhkd &

###
# Configurations
##

# Monitors
bspc HDMI0 -d I II III IV V VI VII VIII IX X
# bspc HDMI1 -d 

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config merge_overlapping_monitors  true

## Window
bspc config border_width                2
bspc config border_radius               5
bspc config window_gap                  8

bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true

## Mouse
bspc config pointer_modifier            mod4 # mod4 = Super_L
bspc config focus_follows_pointer       false
bspc config pointer_follows_focus       false
bspc config pointer_follows_monitor     true

## Colors
bspc config normal_border_color         #262626
bspc config active_border_color         #262626
bspc config focused_border_color        #5F87AF
bspc config presel_feedback_color       #87875F

###
# Rules
##

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

###
# Autostart
##

function run {
    if ! pgrep $1 ; then
        $@&
    fi
}

run xsetroot -cursor_name left_ptr
run $HOME/.scripts/mon r
run $HOME/.config/polybar/launch.sh
run nitrogen --restore
run nm-applet
run dropbox
run xrdb $HOME/.Xresources
run udiskie
run $HOME/.config/picom/launch.sh
run $HOME/.config/conky/launch.sh
