#! /bin/sh

sxhkd &

export CURRENT_DESKTOP=bspwm

###
# Configurations
##

# Monitors
bspc eDP1 -d I II III IV V VI VII
bspc HDMI1 -d VIII IX X

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

bspc config border_width                2
bspc config window_gap                  12

bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true

###
# Rules
##

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

###
# Autostart
##

function run {
    if ! pgrep $1 ; then
        $@&
    fi
}

run $HOME/.config/polybar/launch.sh
run nitrogen --restore
run nm-applet
run dropbox
run xrdb $HOME/.Xresources
run udiskie
run $HOME/.config/compton/launch.sh
run $HOME/.config/conky/launch.sh

