#!/usr/bin/env sh
# A polybar module for dropbox using dropbox-cli

colorRunning="abb2bf"
colorStopped="#555"

dropbox-cli running
isrunning=$?

if [[ $# -gt 0 ]]; then
  case "$1" in
      toggle)
          if [ $isrunning -ne 0 ]; then
              dropbox-cli stop
          else
              dropbox-cli start
          fi
          ;;
          *)
              echo 'error: wrong argument'; exit 1
          ;;
  esac
fi

if [ $isrunning -ne 0 ]; then
    echo "%{F$colorRunning}%{F-}"; exit 0
else
    echo "%{F$colorStopped}%{F-}"; exit 0
fi
